name: Feature
description: Ideas for new features or modifications to existing features
title: "[Feature]: "
assignees:
  - octocat
body:
  - type: input
    id: issue_number
    attributes:
      label: 関連するIssue番号
      description: 関連するIssue番号を入力します
      placeholder: ex. '#1'
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 改修の概要を記載します。
      placeholder: ex. ブログをより簡単に投稿できるようにする。
    validations:
      required: false
  - type: textarea
    id: review_points
    attributes:
      label: レビューポイント
      description: レビュー時に見てほしいポイントを記載します。
      placeholder: ex. postのAPIのテストを確認してください。
  - type: checkboxes
    id: self review
    attributes:
      label: セルフチェック
      options:
        - label: 作成・変更したすべての関数に対して、単体テストを作成した
          required: true
        - label: フロントエンド・バックエンドのいずれもバリデーションを実装した
          required: true
        - label: フロントエンド・バックエンドのいずれもエラーハンドリングを実装した
          required: true
